#!/bin/bash

#! cifar10
# step1:run *5
# python utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack PGD --use_l2 --out_dir ablation/cifar10/l2 >>  ablation/cifar10/l2/PGD.log 2>&1
# python utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack NIFGSM --use_l2 --out_dir  ablation/cifar10/l2 >>  ablation/cifar10/l2/NIFGSM.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --use_l2 --out_dir  ablation/cifar10/l2 >>  ablation/cifar10/l2/MIFGSM.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack PGD --out_dir  ablation/cifar10/nol2 >>  ablation/cifar10/nol2/PGD-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack NIFGSM --out_dir  ablation/cifar10/nol2 >>  ablation/cifar10/nol2/NIFGSM.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --out_dir  ablation/cifar10/nol2 >>  ablation/cifar10/nol2/MIFGSM.log 2>&1
# step2-1 find best eps
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 8 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/eps/eps8.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 32 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/eps/eps32.log 2>&1
# step2-2 find best alpha_atk
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 0.5 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/alpha_atk/alpha05.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 1 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/alpha_atk/alpha1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/alpha_atk/alpha2.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 4 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/alpha_atk/alpha4.log 2>&1
# step2-3 find best steps
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/steps/steps20.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 40 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/steps/steps40.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 60 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/steps/steps60.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 80 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/steps/steps80.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 100 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/steps/steps100.log 2>&1
# step2-4 find best lamda_grad_norm
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/lamda_grad_norm/lamda0.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.001 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/lamda_grad_norm/lamda0001.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.01 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/lamda_grad_norm/lamda001.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/lamda_grad_norm/lamda01-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 1 --out_dir  ablation/find_params/cifar10 >>  ablation/find_params/cifar10/lamda_grad_norm/lamda1-1.log 2>&1
# step3 run final results
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 50 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/cifar10 >>  ablation/final_results/cifar10/buffer50-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 100 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/cifar10 >>  ablation/final_results/cifar10/buffer100-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar10 --buffer_size 200 --csv_log --num_classes 10 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/cifar10 >>  ablation/final_results/cifar10/buffer200-1.log 2>&1

#! cifar100
# step1:run *5
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack PGD --use_l2 --out_dir  ablation/cifar100/l2 >>  ablation/cifar100/l2/PGD.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack NIFGSM --use_l2 --out_dir  ablation/cifar100/l2 >>  ablation/cifar100/l2/NIFGSM.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --use_l2 --out_dir  ablation/cifar100/l2 >>  ablation/cifar100/l2/MIFGSM.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack PGD --out_dir  ablation/cifar100/nol2 >>  ablation/cifar100/nol2/PGD.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack NIFGSM --out_dir  ablation/cifar100/nol2 >>  ablation/cifar100/nol2/NIFGSM.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --out_dir  ablation/cifar100/nol2 >>  ablation/cifar100/nol2/MIFGSM.log 2>&1
# step2-1 find best eps
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 8 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/eps/eps8.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 32 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/eps/eps32.log 2>&1
# step2-2 find best alpha_atk
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 0.5 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/alpha_atk/alpha05.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 1 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/alpha_atk/alpha1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/alpha_atk/alpha2.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 4 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/alpha_atk/alpha4.log 2>&1
# step2-3 find best steps
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/steps/steps20.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 40 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/steps/steps40.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 60 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/steps/steps60.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 80 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/steps/steps80.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 100 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/steps/steps100.log 2>&1
# step2-4 find best lamda_grad_norm
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/lamda_grad_norm/lamda0.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.001 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/lamda_grad_norm/lamda0001.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.01 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/lamda_grad_norm/lamda001.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/lamda_grad_norm/lamda01-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 1 --out_dir  ablation/find_params/cifar100 >>  ablation/find_params/cifar100/lamda_grad_norm/lamda1.log 2>&1
# step3 run final results
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 500  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/cifar100 >>  ablation/final_results/cifar100/buffer500-cat.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 1000  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/cifar100 >>  ablation/final_results/cifar100/buffer1000-cat.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-cifar100 --buffer_size 2000  --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/cifar100 >>  ablation/final_results/cifar100/buffer2000-cat.log 2>&1

#! mini-imagenet
# step1:run *5
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack PGD --use_l2 --out_dir  ablation/miniimg/l2 >>  ablation/miniimg/l2/PGD.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack NIFGSM --use_l2 --out_dir  ablation/miniimg/l2 >>  ablation/miniimg/l2/NIFGSM.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --use_l2 --out_dir  ablation/miniimg/l2 >>  ablation/miniimg/l2/MIFGSM.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack PGD --out_dir  ablation/miniimg/nol2 >>  ablation/miniimg/nol2/PGD.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack NIFGSM --out_dir  ablation/miniimg/nol2 >>  ablation/miniimg/nol2/NIFGSM-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --out_dir  ablation/miniimg/nol2 >>  ablation/miniimg/nol2/MIFGSM-1.log 2>&1
# step2-1 find best eps
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 8 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/eps/eps8.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 32 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/eps/eps32.log 2>&1
# step2-2 find best alpha_atk
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 0.5 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/alpha_atk/alpha05.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 1 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/alpha_atk/alpha1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/alpha_atk/alpha2.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 4 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/alpha_atk/alpha4.log 2>&1
# step2-3 find best steps
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/steps/steps20.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 40 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/steps/steps40.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 60 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/steps/steps60.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 80 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/steps/steps80.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 100 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/steps/steps100.log 2>&1
# step2-4 find best lamda_grad_norm
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/lamda_grad_norm/lamda0.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.001 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/lamda_grad_norm/lamda0001.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.01 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/lamda_grad_norm/lamda001-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/lamda_grad_norm/lamda01-newenv.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 1 --out_dir  ablation/find_params/miniimg >>  ablation/find_params/miniimg/lamda_grad_norm/lamda1-newenv.log 2>&1
# step3 run final results
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 500 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/miniimg >>  ablation/final_results/miniimg/buffer500-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 1000 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/miniimg >>  ablation/final_results/miniimg/buffer1000-1.log 2>&1
# python  utils/main.py --model onlinevt --load_best_args --dataset seq-miniimg --buffer_size 2000 --csv_log --num_classes 100 --num_workers 12 --seed 42 --use_attack --buffer_attack MIFGSM --eps 16 --alpha_atk 2 --steps 20 --lamda_grad_norm 0.1 --out_dir  ablation/final_results/miniimg >>  ablation/final_results/miniimg/buffer2000-1.log 2>&1